-- Coloque scripts iniciais aqui
CREATE TABLE clientes (
     id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     limite integer NOT NULL,
     saldo_inicial integer NOT NULL DEFAULT 0
);

CREATE TABLE transacoes (
     id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     cliente_id   integer REFERENCES clientes(id) NOT NULL,
     tipo  integer NOT NULL,
     descricao varchar(40) NOT NULL CHECK (descricao <> '')
     realizada_em timestamp with time zone DEFAULT current_timestamp
);

DO $$
BEGIN
  INSERT INTO clientes (limite)
  VALUES
    (1000 * 100),
    (800 * 100),
    (10000 * 100),
    (100000 * 100),
    (5000 * 100);
END; $$